name: Deploy Question Analysis Service

on:
  push:
    branches: [main]
    paths:
      - 'question_analysis_service/**'
      - '.github/workflows/deploy-question-analysis.yml'
  workflow_dispatch:

env:
  PROJECT_ID: book-qc-cf
  REGION: us-central1
  SERVICE_NAME: question-analysis-service
  IMAGE_NAME: question-analysis
  REPOSITORY: us-central1-docker.pkg.dev/book-qc-cf/question-analysis

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/282136454082/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'pdf-processor-sa@book-qc-cf.iam.gserviceaccount.com'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker $REGION-docker.pkg.dev
    
    - name: Build Docker image
      run: |
        docker build -t $REPOSITORY/$IMAGE_NAME:$GITHUB_SHA -f question_analysis_service/Dockerfile .
        docker tag $REPOSITORY/$IMAGE_NAME:$GITHUB_SHA $REPOSITORY/$IMAGE_NAME:latest
    
    - name: Push Docker image
      run: |
        docker push $REPOSITORY/$IMAGE_NAME:$GITHUB_SHA
        docker push $REPOSITORY/$IMAGE_NAME:latest
    
    - name: Create Artifact Registry Repository
      run: |
        # Create the question-analysis repository if it doesn't exist
        gcloud artifacts repositories create question-analysis \
          --repository-format=docker \
          --location=$REGION \
          --description="Question Analysis Service Docker Images" \
          --quiet || echo "Repository question-analysis already exists"

    - name: Deploy Cloud Run Job
      run: |
        # Delete existing job if it exists to avoid environment variable conflicts
        if gcloud run jobs describe question-analysis-job --region=$REGION >/dev/null 2>&1; then
          echo "Deleting existing job to avoid environment variable conflicts..."
          gcloud run jobs delete question-analysis-job --region=$REGION --quiet
        fi
        
        # Create new job
        echo "Creating new question-analysis-job..."
        gcloud beta run jobs create question-analysis-job \
          --image=$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA \
          --region=$REGION \
          --service-account=pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,PROJECT_ID=$PROJECT_ID,BUCKET_NAME=book-qc-cf-pdf-storage,REGION=$REGION,VERTEX_AI_LOCATION=$REGION,QDRANT_URL=https://9becb4cf-82b6-456f-ae0c-d797c6c946cc.us-east4-0.gcp.cloud.qdrant.io \
          --max-retries=3 \
          --parallelism=5 \
          --tasks=1 \
          --task-timeout=604800s \
          --memory=4Gi \
          --cpu=2
    
    - name: Deploy Workflow
      run: |
        gcloud workflows deploy question-analysis-workflow \
          --source question_analysis_service/question_analysis_workflow.yaml \
          --location $REGION \
          --service-account pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com
    
    - name: Output deployment information
      run: |
        echo "🚀 Question Analysis Service deployed successfully!"
        echo "📍 Job Name: question-analysis-job"
        echo "📍 Region: $REGION"
        echo "📍 Project: $PROJECT_ID"
        echo "📚 Usage:"
        echo "  - Use Cloud Run Jobs to execute analysis tasks"
        echo "  - Use Cloud Workflows to trigger batch processing"
        echo "  - Use CLI: python question_analysis_service/cli_main.py --help"
