name: Deploy All Services

on:
  push:
    branches: [ main ]
    paths:
      - 'split_pdf_service/**'
      - 'book_extractor_service/**'
      - 'utils/**'
      - 'requirements.txt'
      - 'config.yaml'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  PROJECT_ID: book-qc-cf
  REGION: us-central1
  ARTIFACT_REGISTRY: pdf-processor

jobs:
  deploy-split-pdf:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/282136454082/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'pdf-processor-sa@book-qc-cf.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker $REGION-docker.pkg.dev

    - name: Build and Deploy Split PDF Service
      run: |
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/pdf-processor/pdf-processor:$GITHUB_SHA -f split_pdf_service/Dockerfile .
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/pdf-processor/pdf-processor:$GITHUB_SHA
        
        # Deploy to Cloud Run
        gcloud run deploy pdf-processor \
          --image $REGION-docker.pkg.dev/$PROJECT_ID/pdf-processor/pdf-processor:$GITHUB_SHA \
          --region $REGION \
          --service-account pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com \
          --allow-unauthenticated
        
        # Deploy workflow
        gcloud workflows deploy pdf-processing-workflow \
          --source split_pdf_service/pdf_processing_workflow.yaml \
          --location $REGION \
          --service-account pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com

  deploy-book-extractor:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/282136454082/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'pdf-processor-sa@book-qc-cf.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker $REGION-docker.pkg.dev

    - name: Build and Deploy Book Extractor Service
      run: |
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/book-extractor/book-extractor:$GITHUB_SHA -f book_extractor_service/Dockerfile .
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/book-extractor/book-extractor:$GITHUB_SHA
        
        # Deploy to Cloud Run
        gcloud run deploy book-extractor \
          --image $REGION-docker.pkg.dev/$PROJECT_ID/book-extractor/book-extractor:$GITHUB_SHA \
          --region $REGION \
          --service-account pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com \
          --allow-unauthenticated
        
        # Deploy workflow
        gcloud workflows deploy book-extraction-workflow \
          --source book_extractor_service/book_extraction_workflow.yaml \
          --location $REGION \
          --service-account pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com

  update-workflow-urls:
    runs-on: ubuntu-latest
    needs: [deploy-split-pdf, deploy-book-extractor]
    if: always() && (needs.deploy-split-pdf.result == 'success' || needs.deploy-book-extractor.result == 'success')
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/282136454082/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'pdf-processor-sa@book-qc-cf.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Update Workflow URLs
      run: |
        # Get service URLs
        SPLIT_PDF_URL=$(gcloud run services describe pdf-processor --region=$REGION --format="value(status.url)")
        BOOK_EXTRACTOR_URL=$(gcloud run services describe book-extractor --region=$REGION --format="value(status.url)")
        
        echo "Split PDF Service URL: $SPLIT_PDF_URL"
        echo "Book Extractor Service URL: $BOOK_EXTRACTOR_URL"
        
        # Update split PDF workflow URLs
        if [ -n "$SPLIT_PDF_URL" ]; then
          cd split_pdf_service
          python3 update_workflow_urls.py "$SPLIT_PDF_URL"
          gcloud workflows deploy pdf-processing-workflow \
            --source pdf_processing_workflow.yaml \
            --location $REGION \
            --service-account pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com
        fi
        
        # Update book extractor workflow URLs
        if [ -n "$BOOK_EXTRACTOR_URL" ]; then
          cd book_extractor_service
          python3 update_book_extractor_urls.py "$BOOK_EXTRACTOR_URL"
          gcloud workflows deploy book-extraction-workflow \
            --source book_extraction_workflow.yaml \
            --location $REGION \
            --service-account pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com
        fi
