name: Build and Deploy to GCP Cloud Run (Fallback with Service Account Key)

on:
  workflow_dispatch:
    inputs:
      use_service_account_key:
        description: 'Use service account key instead of WIF'
        required: true
        default: true
        type: boolean

env:
  PROJECT_ID: book-qc-cf
  GAR_LOCATION: us-central1
  REGION: us-central1
  SERVICE: pdf-processor
  REPOSITORY: pdf-processor

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        echo "Tests would run here"
        # python -m pytest tests/

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Google Auth (Service Account Key)
      if: ${{ github.event.inputs.use_service_account_key == 'true' }}
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Google Auth (Workload Identity Federation)
      if: ${{ github.event.inputs.use_service_account_key == 'false' }}
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev
    
    - name: Build and push Docker image
      run: |
        # Build the Docker image
        docker build -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$GITHUB_SHA .
        
        # Push the Docker image
        docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$GITHUB_SHA
        
        # Tag as latest
        docker tag $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$GITHUB_SHA $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:latest
        docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:latest
    
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
        env_vars: |
          PROJECT_ID=${{ env.PROJECT_ID }}
          BUCKET_NAME=book-qc-cf-pdf-storage
          REGION=${{ env.REGION }}
    
    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
