name: Deploy All Services

on:
  push:
    branches: [ main ]
    paths:
      - 'split_pdf_service/**'
      - 'book_extractor_service/**'
      - 'utils/**'
      - 'requirements.txt'
      - 'config.yaml'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  PROJECT_ID: book-qc-cf
  REGION: us-central1
  ARTIFACT_REGISTRY: pdf-processor

jobs:
  deploy-split-pdf:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/282136454082/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'pdf-processor-sa@book-qc-cf.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker $REGION-docker.pkg.dev

    - name: Build and Deploy Split PDF Service
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 15
        max_attempts: 3
        retry_wait_seconds: 60
        command: |
          docker build \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/pdf-processor/pdf-processor:$GITHUB_SHA \
            -f split_pdf_service/Dockerfile .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/pdf-processor/pdf-processor:$GITHUB_SHA
        
    - name: Create/Update Split PDF Cloud Run Job
      run: |
        # Try to update existing job first, if it fails, create a new one
        if gcloud run jobs describe pdf-processor-job --region=$REGION >/dev/null 2>&1; then
          echo "Job exists, updating..."
          gcloud beta run jobs update pdf-processor-job \
            --image=$REGION-docker.pkg.dev/$PROJECT_ID/pdf-processor/pdf-processor:$GITHUB_SHA \
            --region=$REGION \
            --service-account=pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars=PROJECT_ID=$PROJECT_ID,BUCKET_NAME=book-qc-cf-pdf-storage,REGION=$REGION \
            --max-retries=3 \
            --parallelism=5 \
            --tasks=1 \
            --task-timeout=604800s
        else
          echo "Job doesn't exist, creating..."
          gcloud beta run jobs create pdf-processor-job \
            --image=$REGION-docker.pkg.dev/$PROJECT_ID/pdf-processor/pdf-processor:$GITHUB_SHA \
            --region=$REGION \
            --service-account=pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars=PROJECT_ID=$PROJECT_ID,BUCKET_NAME=book-qc-cf-pdf-storage,REGION=$REGION \
            --max-retries=3 \
            --parallelism=5 \
            --tasks=1 \
            --task-timeout=604800s
        fi
        
        # Deploy workflow
        gcloud workflows deploy pdf-processing-workflow \
          --source split_pdf_service/pdf_processing_workflow.yaml \
          --location $REGION \
          --service-account pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com

  deploy-book-extractor:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/282136454082/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'pdf-processor-sa@book-qc-cf.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker $REGION-docker.pkg.dev

    - name: Build and Deploy Book Extractor Service
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 15
        max_attempts: 3
        retry_wait_seconds: 60
        command: |
          docker build \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/book-extractor/book-extractor:$GITHUB_SHA \
            -f book_extractor_service/Dockerfile .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/book-extractor/book-extractor:$GITHUB_SHA
        
    - name: Create/Update Book Extractor Cloud Run Job
      run: |
        # Try to update existing job first, if it fails, create a new one
        if gcloud run jobs describe book-extractor-job --region=$REGION >/dev/null 2>&1; then
          echo "Job exists, updating..."
          gcloud beta run jobs update book-extractor-job \
            --image=$REGION-docker.pkg.dev/$PROJECT_ID/book-extractor/book-extractor:$GITHUB_SHA \
            --region=$REGION \
            --service-account=pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,BUCKET_NAME=book-qc-cf-pdf-storage,VERTEX_AI_LOCATION=$REGION \
            --max-retries=3 \
            --parallelism=5 \
            --tasks=1 \
            --task-timeout=604800s
        else
          echo "Job doesn't exist, creating..."
          gcloud beta run jobs create book-extractor-job \
            --image=$REGION-docker.pkg.dev/$PROJECT_ID/book-extractor/book-extractor:$GITHUB_SHA \
            --region=$REGION \
            --service-account=pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,BUCKET_NAME=book-qc-cf-pdf-storage,VERTEX_AI_LOCATION=$REGION \
            --max-retries=3 \
            --parallelism=5 \
            --tasks=1 \
            --task-timeout=604800s
        fi
        
        # Deploy workflow
        gcloud workflows deploy book-extraction-workflow \
          --source book_extractor_service/book_extraction_workflow.yaml \
          --location $REGION \
          --service-account pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com

  summary:
    runs-on: ubuntu-latest
    needs: [deploy-split-pdf, deploy-book-extractor]
    if: always()
    
    steps:
    - name: Show Deployment Summary
      run: |
        echo "🎉 Deployment Summary:"
        echo "✅ PDF Processor Job: pdf-processor-job"
        echo "✅ Book Extractor Job: book-extractor-job"
        echo "✅ Workflows: pdf-processing-workflow, book-extraction-workflow"
        echo "📍 Region: $REGION"
        echo "📍 Project: $PROJECT_ID"
