name: Build and Deploy Book Extractor

on:
  push:
    branches: [ main ]
    paths:
      - 'book_extractor_service/**'
      - 'requirements.txt'
      - 'utils/**'
  workflow_dispatch:

env:
  PROJECT_ID: book-qc-cf
  REGION: us-central1
  SERVICE_NAME: book-extractor
  BUCKET_NAME: book-qc-cf-pdf-storage
  ARTIFACT_REGISTRY: book-qc-cf-artifacts

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/282136454082/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'pdf-processor-sa@book-qc-cf.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker $REGION-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY/$SERVICE_NAME:$GITHUB_SHA -f book_extractor_service/Dockerfile .

    - name: Push Docker image
      run: |
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY/$SERVICE_NAME:$GITHUB_SHA

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: $SERVICE_NAME
        region: $REGION
        image: $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY/$SERVICE_NAME:$GITHUB_SHA
        flags: --service-account=${{ secrets.SERVICE_ACCOUNT }}

    - name: Deploy GCP Workflow
      run: |
        gcloud workflows deploy book-extraction-workflow \
          --source=book_extractor_service/book_extraction_workflow.yaml \
          --location=$REGION \
          --service-account=pdf-processor-sa@$PROJECT_ID.iam.gserviceaccount.com

    - name: Update Workflow URLs
      run: |
        python book_extractor_service/update_book_extractor_urls.py
